// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEn_Z6qUrrRhkNF4z8TI8I1CzbWJ0-4g',
    appId: '1:385028738237:web:863aa12a34e0b465a6bbd4',
    messagingSenderId: '385028738237',
    projectId: 'firetest-b6634',
    authDomain: 'firetest-b6634.firebaseapp.com',
    storageBucket: 'firetest-b6634.firebasestorage.app',
    measurementId: 'G-CK3E4YP369',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnxGaBBAU5GUD4TzsA9qzk327_SM6ZG40',
    appId: '1:385028738237:android:f118c9a99e1664c3a6bbd4',
    messagingSenderId: '385028738237',
    projectId: 'firetest-b6634',
    storageBucket: 'firetest-b6634.firebasestorage.app',
  );
}
